### PR TITLE
rename `GBP` prefix types to `LCIM`

### LINKED ISSUE #138: duplicate symbol `_GPBExceptionMessageKey `
I use `AVOSCloundIM` and `google protobuf` in the same project and turn on `use_framework!` in pod file.

To avoid the problems introduced by too many dynamic frameworks linked at boot time , we use [cocoapods-amimono](https://github.com/Ruenzuo/cocoapods-amimono) to "Move all dynamic frameworks symbols into the main executable".

When build my project, there are link errors coursed by AVOSCloundIM :
```
duplicate symbol _GPBExceptionMessageKey in:
    Build/Intermediates/Pods.build/Debug-iphonesimulator/AVOSCloudIM.build/Objects-normal/x86_64/LCIMMessage.o
    Build/Intermediates/Pods.build/Debug-iphonesimulator/Protobuf.build/Objects-normal/x86_64/GPBMessage.o
duplicate symbol _GPBWireFormatGetTagFieldNumber in:
duplicate symbol _GPBWireFormatMakeTag in:
duplicate symbol _GPBWireFormatForType in:
duplicate symbol _GPBWireFormatGetTagWireType in:
```

Although, the problem maybe coursed by my special usage, but I recommend to rename the function with GPB, which used by google protobuf, to your own prefix.

### PR DESCRIPTION
**Pull request by leavez**
These symbols may be conflict with Google Protobuf

fix #138

### CODE REVIEW

**Comment by tang3w** [comment]
Thanks for your pull request.

I find that some C types also be renamed, but these are not the symbols that cause link error. These C types are not public, they should not be modified.

We made a fix about this problem 2 days ago (#171), it only renamed some external functions. Would you give it a try? If not working, please provide a detail error log.

**Comment by leavez** [comment]
I write a demo which can show the link errors. https://github.com/leavez/LeanCloudSymbolsConflictDemo

Please check your code on this demo.

**Comment by tang3w** [comment]
I've tested your provided demo, it turns out that the link error has been fixed in #171. You can checkout the modified files in that pull request, and we will publish a new version which includes this patch next week. Thank you so much.

**Comment by leavez** [comment]
I may only checked version 4.0 (specific this git for pod is kind of difficult). Glad it works finally.

**Pull request closed without merging**
